name: CI
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: julia --project -e 'using Pkg; Pkg.instantiate(); Pkg.test()'
